# Generated by Django 4.0.3 on 2022-05-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200)),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.biketype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.bike')),
            ],
        ),
    ]
